import request from 'supertest';
import express from 'express';
import { receiptUpload } from '../../../src/middleware/uploadMiddleware';
import { cleanUploads } from '../../helpers/payments';

// Minimal test app that runs only the upload middleware
const testApp = express();
testApp.post('/upload', (req, res, next) => {
  receiptUpload(req, res, (err) => {
    if (err?.message === 'INVALID_MIME') {
      res.status(400).json({ error: 'INVALID_MIME' });
      return;
    }
    if (err?.code === 'LIMIT_FILE_SIZE') {
      res.status(400).json({ error: 'LIMIT_FILE_SIZE' });
      return;
    }
    if (err) {
      next(err);
      return;
    }
    res.json({ accepted: true, filename: req.file?.filename ?? null });
  });
});

const JPEG = Buffer.from([0xff, 0xd8, 0xff, 0xe0]);
const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47]);
const PDF = Buffer.from('%PDF-1.0\n');
const OVERSIZED = Buffer.alloc(5 * 1024 * 1024 + 100);

afterEach(() => {
  cleanUploads();
});

describe('uploadMiddleware — MIME fileFilter accept/reject matrix', () => {
  describe('accepted MIME types', () => {
    it('accepts image/jpeg', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', JPEG, { filename: 'r.jpg', contentType: 'image/jpeg' });
      expect(res.status).toBe(200);
      expect(res.body.accepted).toBe(true);
      expect(res.body.filename).toMatch(/\.jpg$/);
    });

    it('accepts image/png', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', PNG, { filename: 'r.png', contentType: 'image/png' });
      expect(res.status).toBe(200);
      expect(res.body.accepted).toBe(true);
      expect(res.body.filename).toMatch(/\.png$/);
    });

    it('accepts application/pdf', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', PDF, { filename: 'r.pdf', contentType: 'application/pdf' });
      expect(res.status).toBe(200);
      expect(res.body.accepted).toBe(true);
      expect(res.body.filename).toMatch(/\.pdf$/);
    });
  });

  describe('rejected MIME types', () => {
    it('rejects text/plain', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', Buffer.from('hello'), { filename: 'r.txt', contentType: 'text/plain' });
      expect(res.status).toBe(400);
      expect(res.body.error).toBe('INVALID_MIME');
    });

    it('rejects image/gif', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', Buffer.from('GIF89a'), { filename: 'r.gif', contentType: 'image/gif' });
      expect(res.status).toBe(400);
      expect(res.body.error).toBe('INVALID_MIME');
    });

    it('rejects application/octet-stream', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', Buffer.from('binary'), { filename: 'r.exe', contentType: 'application/octet-stream' });
      expect(res.status).toBe(400);
      expect(res.body.error).toBe('INVALID_MIME');
    });

    it('rejects application/zip', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', Buffer.from('PK'), { filename: 'r.zip', contentType: 'application/zip' });
      expect(res.status).toBe(400);
      expect(res.body.error).toBe('INVALID_MIME');
    });
  });

  describe('file size limit', () => {
    it('rejects file exceeding 5 MB', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', OVERSIZED, { filename: 'big.jpg', contentType: 'image/jpeg' });
      expect(res.status).toBe(400);
      expect(res.body.error).toBe('LIMIT_FILE_SIZE');
    });
  });

  describe('filename generated by multer', () => {
    it('uses UUID-based filename (not original name)', async () => {
      const res = await request(testApp)
        .post('/upload')
        .attach('receipt', JPEG, { filename: 'my-receipt.jpg', contentType: 'image/jpeg' });
      expect(res.status).toBe(200);
      // UUID pattern: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.jpg
      expect(res.body.filename).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.jpg$/,
      );
      expect(res.body.filename).not.toBe('my-receipt.jpg');
    });
  });
});
